### ISSUE TITLE
Criação do modelo de banco de dados

### ISSUE THREAD

**Issue by CeciliaCarol** [suelensalvino/IAC#7]
Modelo BD
Grupo IAC criando o modelo de banco dados, usando o BR Modelo com a finalidade de criar o modelo conceitual para definir as entidades e relações do sistema. Depois usando o MySQL Workbench e criar o modelo lógico para estabelecer a estrutura e organizar os elementos de dados relacionados para depois serem detalhados no banco físico.  

- [x] Modelo Conceitual
- [x] Modelo Logico
- [x] Modelo Físico

**Comment by suelensalvino** [comment]
![BDprojetoIAC](https://user-images.githubusercontent.com/109114160/199957138-57e8ec64-8dad-4055-8553-5d60c5cf60b4.png)



Criação do modelo conceitual

**Comment by Isabela-Alves** [comment]
![IMGBDNOVO](https://user-images.githubusercontent.com/108693206/199961810-cc94b26b-9402-4e69-88dd-57af101f1524.PNG)
Modelo Lógico
